version: "2"
services:
  wordpress:
    build: ./wordpress/wordpress
    ports:
      - 9000:80
    depends_on:
      - wpmysql
    environment:
      WORDPRESS_DB_HOST: "wpmysql:3306"
    env_file:
      ./wordpress/.env
    volumes:
      - htmlroot:/var/www/html
  wpmysql:
    image: mysql:latest
    ports:
      - 3306:3306
    env_file:
      ./wordpress/.env
    volumes:
      - db-data:/var/lib/mysql
      - ./wordpress/db-data/mysql.dump.sql:/docker-entrypoint-initdb.d/install_wordpress.sql
  wpnginx:
    build: ./wordpress/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - ./wordpress/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress/nginx/log:/var/log/nginx
      - htmlroot:/var/www/html
      - ./wordpress/nginx/index.html:/var/www/html/index.html
volumes:
  db-data:
  htmlroot:
