version: "2"
services:
  wordpress:
    build: ./wordpress/wordpress
    restart: always
    ports:
      - '9000:9000'
    links:
      - wpmysql
    depends_on:
      - wpmysql
    environment:
      WORDPRESS_DB_HOST: wpmysql
    env_file:
      ./wordpress/.env
    volumes:
      - htmlroot:/var/www/html
  wpmysql:
    image: mariadb:latest
    restart: always
    ports:
      - '3306:3306'
    env_file:
      ./wordpress/.env
    volumes:
      - db-data:/var/lib/mysql
  wpnginx:
    image: nginx:alpine
    restart: always
    ports:
      - '8080:80'
    links:
      - wordpress
    volumes:
      - htmlroot:/var/www/html
      - ./wordpress/nginx/conf.d:/etc/nginx/conf.d
      - ./wordpress/nginx/log:/var/log/nginx
volumes:
  db-data:
  htmlroot:
