version: "2"
services:
  wordpress:
    build: ./wordpress
    ports:
      - 9080:80
    depends_on:
      - wpmysql
    environment:
      WORDPRESS_DB_HOST: "wpmysql:3306"
    env_file:
      .env
  wpmysql:
    image: mysql:latest
    env_file:
      .env
    volumes:
      - db-data:/var/lib/mysql
      - ./db-data/mysql.dump.sql:/docker-entrypoint-initdb.d/install_wordpress.sql

volumes:
  db-data:
